# Generated by Django 5.0.7 on 2024-08-05 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_api', '0003_orderitem_alter_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
